networks:
    bridge:
        name: my_bridge
        driver: bridge

services:
    bot:
        container_name: my_bot
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        networks:
            - bridge
